# 
# Synthesis run script generated by Vivado
# 

set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
set_msg_config -id {Synth 8-256} -limit 10000
set_msg_config -id {Synth 8-638} -limit 10000
create_project -in_memory -part xcku040-ffva1156-2-e

set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir /home/pyxiong/FPGA_Project/Pulse_clkdomain/Pulse_clkdomain.cache/wt [current_project]
set_property parent.project_path /home/pyxiong/FPGA_Project/Pulse_clkdomain/Pulse_clkdomain.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property board_part xilinx.com:kcu105:part0:1.1 [current_project]
set_property vhdl_version vhdl_2k [current_fileset]
add_files -quiet /home/pyxiong/FPGA_Project/Pulse_clkdomain/Pulse_clkdomain.runs/fifo36x512_synth_1/fifo36x512.dcp
set_property used_in_implementation false [get_files /home/pyxiong/FPGA_Project/Pulse_clkdomain/Pulse_clkdomain.runs/fifo36x512_synth_1/fifo36x512.dcp]
read_verilog -library xil_defaultlib {
  /home/pyxiong/FPGA_Project/Pulse_Stretcher/Pulse_Stretcher.srcs/sources_1/new/Trigger_Catcher.v
  /home/pyxiong/FPGA_Project/Pulse_Stretcher/Pulse_Stretcher.srcs/sources_1/new/Pulse_Generator.v
  /home/pyxiong/FPGA_Project/Pulse_clkdomain/Pulse_clkdomain.srcs/sources_1/new/Registers.v
  /home/pyxiong/FPGA_Project/Pulse_Stretcher/Pulse_Stretcher.srcs/sources_1/new/pulse_stretcher.v
  /home/pyxiong/FPGA_Project/Pulse_clkdomain/Pulse_clkdomain.srcs/sources_1/new/Pulse_clkdomain.v
}
read_vhdl -library xil_defaultlib /home/pyxiong/K7UGbE/src/control_interface.vhd
synth_design -top Pulse_clkdomain -part xcku040-ffva1156-2-e
write_checkpoint -noxdef Pulse_clkdomain.dcp
catch { report_utilization -file Pulse_clkdomain_utilization_synth.rpt -pb Pulse_clkdomain_utilization_synth.pb }
